apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  labels:
    app: journal-api   # <-- add this
spec:
  type: LoadBalancer
  selector:
    app: journal-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000